#!/bin/bash
USAGE="Usage: $0 IP1 IP2 IP3 ..."

if [ "$#" == "0" ]; then
	echo "$USAGE"
	exit 1
fi

MASTER="$1"
while (( "$#" )); do
	if [ "$1" = "$MASTER" ];
	then
		COMMAND="docker run -v ~/data/cassandra:/var/lib/cassandra/data --name cassandra-node -d -e CASSANDRA_BROADCAST_ADDRESS=$1 -p 7000:7000 -p 9042:9042 --health-cmd='bash -c \"cqlsh -e DESCRIBE\ KEYSPACES\;\"' --health-interval=5s --health-timeout=5s --health-retries=2 --health-start-period=10s cassandra"
	else
		COMMAND="docker run -v ~/data/cassandra:/var/lib/cassandra/data --name cassandra-node -d -e CASSANDRA_BROADCAST_ADDRESS=$1 -p 7000:7000 -p 9042:9042 --health-cmd='bash -c \"cqlsh -e DESCRIBE\ KEYSPACES\;\"' --health-interval=5s --health-timeout=5s --health-retries=2 --health-start-period=10s -e CASSANDRA_SEEDS=$MASTER cassandra"
	fi

	ssh student@$1 "docker container stop cassandra-node; docker container rm cassandra-node; $COMMAND;"
	
	while true;
	do
		sleep 5
		STATUS=$(docker exec -it cassandra-node nodetool status | grep -e $1)
		STATUSUN=$(echo $STATUS | grep -e "UN")
		echo $STATUS
		[[ ! -z "$STATUSUN" ]] && break;
	done;
	shift
done

ssh student@$MASTER "docker cp ~/a2group88/cassandra/init.cql cassandra-node:./init.cql"
ssh student@$MASTER "docker exec cassandra-node cqlsh -f ./init.cql"
